"""added validation

Revision ID: 0c155fcac901
Revises: 5218fce01467
Create Date: 2025-11-12 16:13:34.772991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c155fcac901'
down_revision: Union[str, Sequence[str], None] = '5218fce01467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promo_codes', 'discount',
               existing_type=sa.NUMERIC(precision=3, scale=0),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('promo_codes', 'discount',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.NUMERIC(precision=3, scale=0),
               existing_nullable=False)
    # ### end Alembic commands ###
