"""added fild for Product and ProductVariant

Revision ID: 146ee1d75021
Revises: 0c155fcac901
Create Date: 2025-11-15 16:33:04.407630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '146ee1d75021'
down_revision: Union[str, Sequence[str], None] = '0c155fcac901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('hex_color', sa.String(length=256), nullable=True))
    op.add_column('products', sa.Column('new', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('popular', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'popular')
    op.drop_column('products', 'new')
    op.drop_column('product_variants', 'hex_color')
    # ### end Alembic commands ###
