"""fix models in ProductVariant added image and price_variant

Revision ID: 5665602ea879
Revises: 0774ad7cbbdf
Create Date: 2025-11-06 15:00:29.402891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5665602ea879'
down_revision: Union[str, Sequence[str], None] = '0774ad7cbbdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variants', sa.Column('image', sa.Text(), nullable=False))
    op.add_column('product_variants', sa.Column('price_variant', sa.Numeric(), nullable=True))
    op.drop_column('product_variants', 'price')
    op.add_column('products', sa.Column('price', sa.Numeric(), nullable=False))
    op.drop_column('products', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('products', 'price')
    op.add_column('product_variants', sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('product_variants', 'price_variant')
    op.drop_column('product_variants', 'image')
    # ### end Alembic commands ###
